# This file is a template, and might need editing before it works on your project.
default:
  image: tmtmt/rust-wasm-bindgen

install_package:
  stage: build
  script:
    - npm install --unsafe-perm
  artifacts:
    paths:
      - node_modules
      - dist

test_package:
  stage: test
  script:
    - npm test

publish_package:
  stage: deploy
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish
  only:
    - release

