default:
  image: node:latest

install_package:
  stage: build
  script:
    - npm install

test_package:
  stage: test
  script:
    - npm test

publish_package:
  stage: deploy
  script:
    - npm publish
  only:
    - release
